const { expect, test } = require('@playwright/test')
test.describe.configure({ mode: 'serial' })
let publishedTestRule
test.afterEach(async ({ page }) => {
  for (const input of await page.locator('input[type="password"]').all()) await input.fill('')
})

test('真实设计器：页面创建、纯编译、草稿新增覆盖、提交审批并生成正式版本', async ({ page }, testInfo) => {
  test.skip(process.env.E2E_DESIGNER_LIVE !== '1', '显式开启本地设计器验证后才创建测试规则')
  test.setTimeout(180000)
  page.setDefaultTimeout(15000)
  const base = 'http://localhost:9092'
  const failures = [], writes = []
  page.on('pageerror', error => failures.push(error.message))
  page.on('console', message => { if (message.type() === 'error') failures.push(message.text()) })
  page.on('request', request => { if (request.method() === 'POST') writes.push(new URL(request.url()).pathname) })
  await page.setViewportSize({ width: 1600, height: 1000 })
  await page.goto(`${base}/#/rule?projectId=1`)
  await expect(page.locator('.layout-sidebar, input[autocomplete="username"]').first()).toBeVisible()
  if (page.url().includes('#/login')) {
    await page.locator('input[autocomplete="username"]').fill(process.env.E2E_USERNAME)
    await page.locator('input[autocomplete="current-password"]').fill(process.env.E2E_PASSWORD)
    const loginResponse = page.waitForResponse(response => response.url().includes('/auth/console/login'))
    await page.locator('button[type="submit"]').click()
    const login = await (await loginResponse).json()
    expect(login.code, login.message).toBe(200)
    console.log('UI login succeeded')
  }
  await expect(page.locator('.layout-sidebar')).toBeVisible()
  await page.getByRole('button', { name: '新建规则', exact: true }).click()
  const create = page.getByRole('dialog', { name: '新建规则', exact: true })
  const code = `designer_check_${Date.now()}`
  await create.getByRole('textbox', { name: '规则编码' }).fill(code)
  await create.getByRole('textbox', { name: '规则名称' }).fill(`设计器回归 ${code}`)
  await create.locator('.el-form-item').filter({ hasText: '模型类型' }).locator('.el-select').click()
  await page.getByRole('option', { name: 'QL脚本', exact: true }).click()
  const createdResponse = page.waitForResponse(response => new URL(response.url()).pathname === '/api/rule/definition' && response.request().method() === 'POST')
  await create.getByRole('button', { name: '创建并继续配置', exact: true }).click()
  const created = await (await createdResponse).json()
  expect(created.code).toBe(200)
  const id = String(created.data.id)
  console.log(`UI-created verification rule: ${id} (${code})`)
  await expect(page).toHaveURL(new RegExp(`/designer/script/${id}`))
  const bar = page.locator('main .rule-designer-actions')
  await expect(bar.locator('[data-action="test"]')).toBeEnabled()
  const editor = page.getByRole('textbox', { name: /Editor content/ }).first()
  const edit = async script => { await editor.click(); await editor.press('ControlOrMeta+A'); await editor.fill(script) }
  await edit('return 7;')
  const draftPath = `/api/rule/definition/${id}/designer/drafts`
  const responseFor = path => page.waitForResponse(response => new URL(response.url()).pathname === path && response.request().method() === 'POST')
  const compiledResponse = responseFor(`/api/rule/definition/${id}/designer/compile`)
  await bar.locator('[data-action="compile"]').click()
  const compiled = await (await compiledResponse).json()
  expect(compiled.data.compileSuccess).toBe(true)
  expect(compiled.data.compiledScript).toContain('return 7;')
  expect(compiled.data.preflightReport.valid).toBe(true)
  expect(writes.filter(path => path === draftPath)).toHaveLength(0)
  let savedResponse = responseFor(draftPath)
  await bar.locator('[data-action="save"]').click()
  const first = await (await savedResponse).json()
  expect(first.code).toBe(200)
  const draftId = String(first.data.revision.id)
  await expect(page).toHaveURL(new RegExp(`sourceId=${draftId}`))
  await edit('return 8;')
  await bar.locator('[data-action="save"]').click()
  const save = page.getByRole('dialog', { name: '保存草稿', exact: true })
  await save.getByText('覆盖当前草稿', { exact: true }).click()
  savedResponse = responseFor(draftPath)
  await save.locator('[data-action="confirm-save"]').click()
  const overwrite = await (await savedResponse).json()
  expect(String(overwrite.data.revision.id)).toBe(draftId)
  expect(overwrite.data.revision.lockVersion).toBeGreaterThan(first.data.revision.lockVersion)
  expect(JSON.parse(overwrite.data.revision.modelJson).script).toBe('return 8;')
  await expect(page.getByTestId('designer-info')).toContainText('草稿已保存')
  await bar.locator('[data-action="test"]').click()
  const dialog = page.getByRole('dialog', { name: '测试执行', exact: true })
  await dialog.getByRole('button', { name: '执行测试', exact: true }).click()
  await expect(dialog).toContainText('执行成功')
  await dialog.getByRole('button', { name: '关闭', exact: true }).click()
  await bar.locator('[data-action="publish"]').click()
  const publish = page.getByRole('dialog', { name: '发布规则', exact: true })
  await expect(publish).toBeVisible()
  await publish.getByRole('textbox', { name: '变更说明' }).fill('本地设计器端到端验证')
  const submittedResponse = responseFor(`/api/rule/definition/${id}/designer/publish`)
  await publish.locator('[data-action="confirm-publish"]').click()
  const submitted = await (await submittedResponse).json()
  expect(submitted.code).toBe(200)
  expect(submitted.data.revision.state).toBe('REVIEW')
  const requestId = submitted.data.approvalRequestId
  console.log(`UI-submitted verification approval: ${requestId}`)
  await page.goto(`${base}/#/approval/${requestId}`)
  await page.getByRole('button', { name: '通过并生效', exact: true }).click()
  const approve = page.getByRole('dialog', { name: '通过并立即生效', exact: true })
  await approve.getByRole('textbox').fill('确认本地测试规则，验证发布原子性')
  await approve.getByRole('button', { name: '确认', exact: true }).click()
  await expect(page.locator('.header-meta')).toContainText('已通过', { timeout: 30000 })
  await page.goto(`${base}/#/designer/script/${id}?projectId=1`)
  await expect(page.getByTestId('designer-version-select')).toContainText('发布版本 v1')
  await expect(editor).toHaveValue('return 8;')
  // Editing production always creates another draft; NEW publication allocates v2 only after approval.
  const publishAndApprove = async (mode, version) => {
    await bar.locator('[data-action="publish"]').click()
    const publishDialog = page.getByRole('dialog', { name: '发布规则', exact: true })
    await expect(publishDialog).toBeVisible()
    if (mode === 'OVERWRITE') {
      await publishDialog.getByText('覆盖已有版本', { exact: true }).click()
      await publishDialog.getByText('选择覆盖版本', { exact: true }).click()
      await page.getByRole('option', { name: `版本 v${version}`, exact: true }).click()
    }
    await publishDialog.getByRole('textbox', { name: '变更说明' }).fill('版本绑定回归验证')
    const submittedResponse = responseFor(`/api/rule/definition/${id}/designer/publish`)
    await publishDialog.locator('[data-action="confirm-publish"]').click()
    const submission = await (await submittedResponse).json()
    expect(submission.code, submission.message).toBe(200)
    console.log(`UI version ${mode} approval: ${submission.data.approvalRequestId}`)
    await page.goto(`${base}/#/approval/${submission.data.approvalRequestId}`)
    await page.getByRole('button', { name: '通过并生效', exact: true }).click()
    const approveDialog = page.getByRole('dialog', { name: '通过并立即生效', exact: true })
    await approveDialog.getByRole('textbox').fill('确认版本绑定回归测试')
    await approveDialog.getByRole('button', { name: '确认', exact: true }).click()
    await expect(page.locator('.header-meta')).toContainText('已通过', { timeout: 30000 })
    const versionsResponse = page.waitForResponse(response => new URL(response.url()).pathname === `/api/rule/definition/${id}/published-versions`)
    await page.goto(`${base}/#/designer/script/${id}?projectId=1`)
    return (await (await versionsResponse).json()).data
  }
  await edit('return 10;')
  savedResponse = responseFor(draftPath)
  await bar.locator('[data-action="save"]').click()
  const second = await (await savedResponse).json()
  expect(second.code).toBe(200)
  expect(String(second.data.revision.id)).not.toBe(draftId)
  let versions = await publishAndApprove('NEW')
  expect(versions.map(version => version.version)).toEqual([2, 1])
  await expect(page.getByTestId('designer-version-select')).toContainText('发布版本 v2')
  await edit('return 11;')
  versions = await publishAndApprove('OVERWRITE', 1)
  expect(versions.map(version => version.version)).toEqual([2, 1])
  expect(versions.find(version => version.version === 1).generation).toBe(2)
  await expect(page.getByTestId('designer-version-select')).toContainText('发布版本 v2')
  await expect(editor).toHaveValue('return 10;')
  await page.getByTestId('designer-version-select').click()
  await page.getByRole('option', { name: '发布版本 v1', exact: true }).click()
  await expect(editor).toHaveValue('return 11;')
  await page.screenshot({ path: testInfo.outputPath('real-designer-published.png') })
  publishedTestRule = { id, versions }
  expect(failures).toEqual([])
})

test('真实执行最新与指定版本，并在删除最后草稿后恢复空白设计', async ({ page }) => {
  test.skip(process.env.E2E_DESIGNER_LIVE !== '1', '仅显式运行本地验证')
  test.setTimeout(120000)
  page.setDefaultTimeout(15000)
  const base = 'http://localhost:9092'
  const failures = []
  page.on('pageerror', error => failures.push(error.message))
  page.on('console', message => { if (message.type() === 'error') failures.push(message.text()) })
  await page.goto(`${base}/#/rule?projectId=1`)
  await page.locator('input[autocomplete="username"]').fill(process.env.E2E_USERNAME)
  await page.locator('input[autocomplete="current-password"]').fill(process.env.E2E_PASSWORD)
  await page.locator('button[type="submit"]').click()
  await expect(page.locator('.layout-sidebar')).toBeVisible()
  await page.getByRole('button', { name: '新建规则', exact: true }).click()
  const create = page.getByRole('dialog', { name: '新建规则', exact: true })
  const code = `designer_caller_${Date.now()}`
  await create.getByRole('textbox', { name: '规则编码' }).fill(code)
  await create.getByRole('textbox', { name: '规则名称' }).fill(`版本调用回归 ${code}`)
  await create.locator('.el-form-item').filter({ hasText: '模型类型' }).locator('.el-select').click()
  await page.getByRole('option', { name: 'QL脚本', exact: true }).click()
  const responseFor = path => page.waitForResponse(response => new URL(response.url()).pathname === path && response.request().method() === 'POST')
  const createdResponse = responseFor('/api/rule/definition')
  await create.getByRole('button', { name: '创建并继续配置', exact: true }).click()
  const created = await (await createdResponse).json()
  expect(created.code).toBe(200)
  const id = String(created.data.id)
  console.log(`UI-created caller verification rule: ${id}`)
  const bar = page.locator('main .rule-designer-actions')
  await expect(bar.locator('[data-action="test"]')).toBeEnabled()
  const editor = page.getByRole('textbox', { name: /Editor content/ }).first()
  const fixed = publishedTestRule.versions.find(version => version.version === 1)
  await editor.click(); await editor.press('ControlOrMeta+A')
  await editor.fill(`return executeRuleById("${publishedTestRule.id}") * 100 + executeRuleVersionById("${publishedTestRule.id}", "${fixed.bindingId}");`)
  await bar.locator('[data-action="compile"]').click()
  await expect(page.getByTestId('designer-info')).toContainText('编译与发布前检查通过')
  await bar.locator('[data-action="test"]').click()
  const dialog = page.getByRole('dialog', { name: '测试执行', exact: true })
  const executedResponse = responseFor('/api/rule/definition/execute')
  await dialog.getByRole('button', { name: '执行测试', exact: true }).click()
  const executed = await (await executedResponse).json()
  expect(executed.data.success, executed.data.errorMessage).toBe(true)
  expect(executed.data.result).toBe(1011)
  await dialog.getByRole('button', { name: '关闭', exact: true }).click()
  const savedResponse = responseFor(`/api/rule/definition/${id}/designer/drafts`)
  await bar.locator('[data-action="save"]').click()
  const saved = await (await savedResponse).json()
  expect(saved.code).toBe(200)
  await expect(page).toHaveURL(new RegExp(`sourceId=${saved.data.revision.id}`))
  await page.getByTestId('designer-version-select').click()
  await page.getByRole('button', { name: /^删除草稿/ }).click()
  await page.getByRole('dialog', { name: '删除草稿', exact: true }).getByRole('button', { name: '删除草稿', exact: true }).click()
  await expect(page.getByTestId('designer-info')).toContainText('已加载，尚未修改')
  await expect(editor).toHaveValue('')
  await page.reload()
  await expect(bar.locator('[data-action="test"]')).toBeEnabled()
  await expect(editor).toHaveValue('')
  expect(failures).toEqual([])
})
