const { expect, test } = require('@playwright/test')
const { installDistRoutes } = require('./support/distRoutes.cjs')
const { createDetailApiData } = require('./support/detailFixtures.cjs')
const { createManagementApiData } = require('./support/managementFixtures.cjs')
const { createDesignerApiData } = require('./support/designerFixtures.cjs')

function fixtures() { return new Map([...createManagementApiData(), ...createDetailApiData()]) }

test('A08 工作台只读角色可查看规则，但不可进入无权限字段模块', async ({ page }) => {
  const data = fixtures()
  data.set('/api/auth/console/config', { loginEnabled: true })
  data.set('/api/auth/console/me', { username: 'reviewer', permissions: ['project:view', 'rule:view'] })
  data.set('/api/auth/console/preferences/theme', null)
  const { assertClean } = await installDistRoutes(page, { apiData: data })
  await page.goto('http://tianshu.local/index.html#/project/1')
  await expect(page.locator('.quick-actions').getByRole('button', { name: '业务字段', exact: true })).toBeDisabled()
  await expect(page.getByText(/灰色入口表示当前账号没有对应模块/)).toBeVisible()
  await page.locator('.quick-actions').getByRole('button', { name: '规则设计', exact: true }).click()
  await expect(page).toHaveURL(/#\/rule\?projectId=1$/)
  assertClean()
})

test('A13 变量表保留关键列，更多列可展开，行内操作直接可用', async ({ page }, testInfo) => {
  const { assertClean } = await installDistRoutes(page, { apiData: fixtures() })
  await page.setViewportSize({ width: 1280, height: 720 })
  await page.goto('http://tianshu.local/index.html#/variable?projectId=1')
  const table = page.locator('.var-list-section .el-table')
  await expect(table.locator('th').filter({ hasText: '脚本名称' })).toHaveCount(0)
  await page.getByText('显示脚本名称、默认值和取值范围', { exact: true }).click()
  await expect(table.locator('th').filter({ hasText: '脚本名称' })).toHaveCount(1)
  await page.getByText('显示脚本名称、默认值和取值范围', { exact: true }).click()
  await expect(table.locator('.el-dropdown')).toHaveCount(0)
  const row = table.locator('.el-table__body tr').first()
  await row.getByRole('button', { name: '转全局', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '转为全局', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await row.getByRole('button', { name: '删除', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '确认删除', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await page.screenshot({ path: testInfo.outputPath('variable-columns.png') })
  assertClean()
})

for (const entry of ['project/1', 'rule?projectId=1']) {
  test(`A14 ${entry} 创建后直接继续配置`, async ({ page }) => {
    const data = new Map([...fixtures(), ...createDesignerApiData()])
    data.set('/api/rule/definition/101', { id: 101, projectId: 1, scope: 'PROJECT', modelType: 'SCRIPT', ruleCode: 'Mixed_Case_New' })
    data.set('/api/rule/definition/101/revisions', [])
    data.set('/api/rule/definition/versions/101', [])
    data.set('/api/rule/definition/101/published-versions', [])
    data.set('/api/rule/definition/content/101', { definitionId: 101, modelJson: '{"script":""}' })
    let submitted
    let savedDraft
    data.set('POST /api/rule/definition/101/designer/drafts', ({ request }) => {
      savedDraft = request.postDataJSON()
      return { revision: { id: 901, definitionId: 101, state: 'DRAFT', lockVersion: 1, revisionNo: 1, modelJson: savedDraft.modelJson }, compileSuccess: true, issues: [] }
    })
    data.set('POST /api/rule/definition', ({ request }) => { submitted = request.postDataJSON(); return { id: 101 } })
    const { requests, assertClean } = await installDistRoutes(page, { apiData: data })
    await page.goto('http://tianshu.local/index.html#/' + entry)
    if (entry.startsWith('project')) await page.getByRole('tab', { name: '项目规则', exact: true }).click()
    await page.getByRole('button', { name: '新建规则', exact: true }).click()
    const dialog = page.getByRole('dialog', { name: '新建规则' })
    await dialog.getByRole('textbox', { name: '规则编码' }).fill('Mixed_Case_New')
    await dialog.getByRole('textbox', { name: '规则名称' }).fill('继续配置验证')
    await dialog.locator('.el-form-item').filter({ hasText: '模型类型' }).locator('.el-select').click()
    await page.getByRole('option', { name: 'QL脚本', exact: true }).click()
    await dialog.getByRole('button', { name: '创建并继续配置', exact: true }).click()
    await expect(page).toHaveURL(/#\/designer\/script\/101\?projectId=1$/)
    expect(submitted.ruleCode).toBe('Mixed_Case_New')
    await expect(page.getByRole('button', { name: '保存', exact: true })).toBeVisible()
    await page.locator('.se-var-item').filter({ hasText: 'age' }).first().dblclick()
    await expect(page.getByRole('textbox', { name: /Editor content/ })).toHaveValue('age')
    expect(requests.filter(request => request.method === 'POST')).toHaveLength(1)
    expect(savedDraft).toBeUndefined()
    await page.getByRole('button', { name: '保存', exact: true }).click()
    await expect(page.getByRole('status')).toContainText('草稿已保存')
    expect(JSON.parse(savedDraft.modelJson).script).toBe('age')
    expect(savedDraft.sourceType).toBeUndefined()
    expect(savedDraft.sourceId).toBeUndefined()
    await expect(page).toHaveURL(/projectId=1.*sourceType=REVISION.*sourceId=901/)
    assertClean()
  })
}

test('A09 A11 数据库字段通过参数表单、结果选择和审批草稿保存配置', async ({ page }, testInfo) => {
  const data = fixtures()
  const age = { id: 1, projectId: 1, scope: 'PROJECT', status: 1, varCode: 'age', scriptName: 'age', varLabel: '年龄', varType: 'INTEGER', varSource: 'INPUT' }
  data.set('/api/rule/variable/project/1', [age])
  data.set('/api/rule/dataobject/tree/1', [])
  data.set('/api/rule/function/project/1/all', [])
  data.set('/api/rule/model/project/1/all', [])
  data.set('/api/rule/variable/source-options', { apiOptions: [], databaseOptions: [{ id: 31, code: 'risk_mysql', name: '风控只读库', scope: 'PROJECT', projectId: 1 }], listOptions: [] })
  let preview
  let submitted
  data.set('POST /api/rule/variable/preview', ({ request }) => {
    preview = request.postDataJSON()
    return { resolvedValue: 88, databaseRows: [{ score: 88, level: 'A' }] }
  })
  data.set('POST /api/rule/governance/drafts', ({ request }) => {
    submitted = request.postDataJSON()
    return { id: 991 }
  })
  data.set('/api/rule/governance/requests/991', { id: 991, resourceType: 'VARIABLE', status: 'DRAFT', action: 'CREATE', projectId: 1, dependencies: [], preflightReport: null })
  const { assertClean } = await installDistRoutes(page, { apiData: data })
  await page.setViewportSize({ width: 1280, height: 720 })
  await page.goto('http://tianshu.local/index.html#/variable?projectId=1')
  await page.getByRole('button', { name: '新建字段', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '新建字段' })
  await dialog.getByRole('button', { name: /数据库查询/ }).click()
  await dialog.locator('.el-form-item').filter({ hasText: '字段编码' }).locator('input').fill('Query_Score')
  await dialog.locator('.el-form-item').filter({ hasText: '字段名称' }).locator('input').fill('数据库评分')
  await dialog.locator('.el-form-item').filter({ hasText: '数据库源' }).locator('.el-select').click()
  await page.getByRole('option', { name: /风控只读库/ }).click()
  await dialog.locator('.el-form-item').filter({ hasText: '查询 SQL' }).locator('.monaco-editor-container').click()
  const sql = "/* query ; ? */ SELECT ? AS age, ? AS code;"
  await page.keyboard.insertText(sql)
  await dialog.getByRole('button', { name: '补齐参数', exact: true }).click()
  const rows = dialog.locator('.sql-param-row')
  await rows.nth(0).locator('.el-select').first().click()
  await page.getByRole('option', { name: '业务字段', exact: true }).click()
  await rows.nth(0).locator('.el-select').last().click()
  await page.getByRole('option', { name: /年龄/ }).click()
  await rows.nth(1).getByRole('textbox', { name: '参数 2 值' }).fill('001')
  await dialog.getByRole('textbox', { name: '样例 年龄' }).fill('28')
  await dialog.getByRole('button', { name: '预览取值', exact: true }).click()
  await expect(dialog.getByText('查询返回 1 行', { exact: true })).toBeVisible()
  await dialog.locator('.db-preview-rows .el-select').click()
  await page.getByRole('option', { name: '第 1 行 · score', exact: true }).click()
  await expect(dialog.locator('.el-form-item').filter({ hasText: '结果路径' }).locator('input')).toHaveValue('0.score')
  await dialog.getByRole('button', { name: '预览取值', exact: true }).click()
  await expect(dialog.getByText('查询返回 1 行', { exact: true })).toBeVisible()
  expect(preview.params).toEqual({ age: 28 })
  await page.screenshot({ path: testInfo.outputPath('database-variable-form.png') })
  await dialog.getByRole('button', { name: '生成审批草稿', exact: true }).click()
  await expect(page).toHaveURL(/#\/approval\/991$/)
  const variable = JSON.parse(submitted.snapshotJson)
  const config = JSON.parse(variable.sourceConfig)
  expect(variable.varCode).toBe('Query_Score')
  expect(config.sql).toBe(sql)
  expect(config.resultPath).toBe('0.score')
  expect(config.params[0]).toEqual(expect.objectContaining({ kind: 'REFERENCE', refId: 1, refType: 'VARIABLE' }))
  expect(config.params[1]).toEqual({ kind: 'LITERAL', valueType: 'STRING', value: '001' })
  assertClean()
})

test('A07 从校验报告进入确切修订并定位决策表规则行', async ({ page }, testInfo) => {
  const data = new Map([...fixtures(), ...createDesignerApiData()])
  const model = { rules: [{ conditionOperator: 'AND', conditions: [], actions: [] }] }
  const revision = { id: 2101, definitionId: 101, revisionNo: 1, state: 'DRAFT', lockVersion: 0, modelJson: JSON.stringify(model) }
  data.set('/api/rule/definition/detail/101', { ...fixtures().get('/api/rule/definition/detail/101'), modelType: 'TABLE' })
  data.set('/api/rule/definition/101/revisions', [revision])
  data.set('/api/rule/definition/101/revisions/2101', revision)
  data.set('/api/rule/definition/content/101', { definitionId: 101, modelJson: revision.modelJson })
  data.set('POST /api/rule/definition/101/revisions/2101/preflight', { revisionId: 2101, valid: false, errors: [{ code: 'MISSING_REFERENCE_ID', message: '请重新选择条件字段', path: '$.rules[0].conditions[0]', revisionId: 2101 }] })
  const { assertClean } = await installDistRoutes(page, { apiData: data })
  await page.goto('http://tianshu.local/index.html#/rule/101')
  await page.getByRole('button', { name: '发布前校验', exact: true }).click()
  await page.getByRole('button', { name: '定位到规则设计', exact: true }).click()
  await expect(page).toHaveURL(/#\/designer\/table\/101\?.*sourceId=2101/)
  await expect(page.getByText(/校验定位 · 第 1 个规则行/)).toBeVisible()
  await page.getByRole('button', { name: '定位问题', exact: true }).click()
  await expect(page.locator('[data-validation-path="$.rules[0]"]')).toBeFocused()
  await page.screenshot({ path: testInfo.outputPath('validation-location.png') })
  assertClean()
})
