const fs = require('node:fs')
const net = require('node:net')
const password = fs.readFileSync('.env', 'utf8').split(/\r?\n/).find(x => x.startsWith('REDIS_PASSWORD=')).slice(15)
const socket = net.createConnection(6379, '192.168.71.106')
socket.setTimeout(3000)
socket.on('connect', () => socket.write('*2\r\n$4\r\nAUTH\r\n$' + Buffer.byteLength(password) + '\r\n' + password + '\r\n*1\r\n$4\r\nPING\r\n'))
socket.on('data', data => { console.log(data.toString()); if (data.toString().includes('PONG') || data.toString().includes('ERR')) socket.end() })
socket.on('timeout', () => { console.log('timeout'); socket.destroy() })
socket.on('error', e => console.log(e.message))
