packages:
  - .

allowBuilds:
  '@parcel/watcher': set this to true or false
  core-js: set this to true or false
  deasync: set this to true or false
  ejs: set this to true or false
  fsevents: set this to true or false
  yorkie: set this to true or false

overrides:
  '@babel/preset-env': 7.12.17
